version: '2'
services:
    imageboard-app:
        image: imageboard
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://imageboard-mysql:3306/imageboard?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    imageboard-mysql:
        extends:
            file: mysql.yml
            service: imageboard-mysql
